apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mobile-web
  namespace: argocd
spec:
  project: default   # ðŸ‘ˆ THIS LINE IS REQUIRED

  source:
    repoURL: https://github.com/vikasrajput0112/mobile-web.git
    targetRevision: main
    path: k8s-gitops

  destination:
    server: https://kubernetes.default.svc
    namespace: mobile-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
