apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mobile-web
  template:
    metadata:
      labels:
        app: mobile-web
    spec:
      containers:
      - name: mobile-web
        image: ghcr.io/vikasrajput0112/mobile-web:{{TAG}}
        ports:
        - containerPort: 80
