apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mobile-web
spec:
  rules:
  - host: mobile.test.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mobile-web
            port:
              number: 80
