apiVersion: v1
kind: Service
metadata:
  name: mobile-web
  namespace: mobile-app
spec:
  type: NodePort
  selector:
    app: mobile-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30084
